# Generated by Django 4.0.5 on 2022-08-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='Description',
            field=models.TextField(),
        ),
    ]
